on:
  schedule:
  - cron: '0 */6 * * *'

jobs:
  RSS-to-Zulip:
    timeout-minutes: 10
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - run: |-
        pip install \
         feedparser \
         markdownify \
         git+https://github.com/i-ky/python-zulip-api.git@markdownify#subdirectory=zulip
        
        for FEED in feeds/*; do
          echo "Processing $FEED"
          TOPIC=$(cat "$FEED/topic-name")

          $HOME/.local/share/zulip/integrations/rss/rss-bot \
          --markdownify \
          --site '${{ secrets.zulip_organization_url }}' \
          --api-key '${{ secrets.zulip_bot_key }}' \
          --user '${{ secrets.zulip_bot_email }}' \
          --feed-file "$FEED/rss-feeds" \
          --data-dir "$FEED/" \
          --topic "$TOPIC" \
          --stream RSS
        done

        git config --global user.email "zulip-rss-bot@users.noreply.github.com"
        git config --global user.name "RSS Bot"
        git add --all
        git commit --allow-empty -m "Update hashes."
        git gc
        git remote add origin2 https://${GITHUB_ACTOR}:${{ secrets.GITHUB_TOKEN }}@github.com/${GITHUB_REPOSITORY}
        git push origin2 HEAD:main
